/**
 * FoodConnect — Realistic Prototype Seed Data (Visakhapatnam Pilot)
 *
 * Source of truth for local mock repositories. All records are clearly marked
 * as demonstration/seed data while preserving the complete relational schema
 * defined in docs/database-architecture.md and types/database.ts.
 */

import {
  IUser,
  IDonorProfile,
  INGOProfile,
  INeed,
  IDonation,
  IMatch,
  ICollection,
  IDistribution,
  IAuditLog,
  INotification,
} from "@/types/database"

// Base timestamps for coherent relative time calculations
const now = new Date()
const hourAgo = (h: number) => new Date(now.getTime() - h * 60 * 60 * 1000)
const hoursFromNow = (h: number) => new Date(now.getTime() + h * 60 * 60 * 1000)
const daysAgo = (d: number) => new Date(now.getTime() - d * 24 * 60 * 60 * 1000)

// ============================================================================
// 1. MOCK USERS (AUTHENTICATION & IDENTITIES)
// ============================================================================

export const SEED_USERS: IUser[] = [
  // Donors
  {
    _id: "usr-donor-01",
    name: "Venkata Raman (Hotel Daspalla)",
    email: "fnb@daspallavizag.demo",
    phone: "+918912564800",
    passwordHash: "$argon2id$mock-hash-daspalla-donor",
    role: "DONOR",
    accountStatus: "ACTIVE",
    emailVerified: true,
    phoneVerified: true,
    lastLoginAt: hourAgo(2),
    createdAt: daysAgo(30),
    updatedAt: daysAgo(5),
  },
  {
    _id: "usr-donor-02",
    name: "Executive Chef Ananya Roy (Novotel)",
    email: "culinary@novotelvizag.demo",
    phone: "+918913045600",
    passwordHash: "$argon2id$mock-hash-novotel-donor",
    role: "DONOR",
    accountStatus: "ACTIVE",
    emailVerified: true,
    phoneVerified: true,
    lastLoginAt: hourAgo(4),
    createdAt: daysAgo(20),
    updatedAt: daysAgo(2),
  },
  {
    _id: "usr-donor-03",
    name: "K. Satyanarayana (Vizag Bakers Guild)",
    email: "orders@vizagbakers.demo",
    phone: "+918912781200",
    passwordHash: "$argon2id$mock-hash-bakers-donor",
    role: "DONOR",
    accountStatus: "ACTIVE",
    emailVerified: true,
    phoneVerified: false,
    lastLoginAt: hourAgo(12),
    createdAt: daysAgo(15),
    updatedAt: daysAgo(1),
  },
  {
    _id: "usr-donor-04",
    name: "Murthy Catering Services",
    email: "catering@murthyvizag.demo",
    phone: "+918912554400",
    passwordHash: "$argon2id$mock-hash-murthy-donor",
    role: "DONOR",
    accountStatus: "ACTIVE",
    emailVerified: true,
    phoneVerified: true,
    lastLoginAt: daysAgo(1),
    createdAt: daysAgo(40),
    updatedAt: daysAgo(10),
  },

  // NGOs
  {
    _id: "usr-ngo-01",
    name: "Dr. P. S. Sarma (Sneha Sandhya Trust)",
    email: "trust@snehasandhya.demo",
    phone: "+918912789456",
    passwordHash: "$argon2id$mock-hash-sandhya-ngo",
    role: "NGO",
    accountStatus: "ACTIVE",
    emailVerified: true,
    phoneVerified: true,
    lastLoginAt: hourAgo(1),
    createdAt: daysAgo(60),
    updatedAt: daysAgo(2),
  },
  {
    _id: "usr-ngo-02",
    name: "Sister Mary Vasantha (Prema Samajam)",
    email: "care@premasamajam.demo",
    phone: "+918912567890",
    passwordHash: "$argon2id$mock-hash-prema-ngo",
    role: "NGO",
    accountStatus: "ACTIVE",
    emailVerified: true,
    phoneVerified: true,
    lastLoginAt: hourAgo(3),
    createdAt: daysAgo(50),
    updatedAt: daysAgo(3),
  },
  {
    _id: "usr-ngo-03",
    name: "K. Appa Rao (Ashray Kitchen)",
    email: "kitchen@ashraygajuwaka.demo",
    phone: "+918912445566",
    passwordHash: "$argon2id$mock-hash-ashray-ngo",
    role: "NGO",
    accountStatus: "ACTIVE",
    emailVerified: true,
    phoneVerified: true,
    lastLoginAt: hourAgo(5),
    createdAt: daysAgo(45),
    updatedAt: daysAgo(4),
  },
  {
    _id: "usr-ngo-04",
    name: "M. Jagannath (Sankalp Coastal Trust)",
    email: "contact@sankalpcoast.demo",
    phone: "+918912889900",
    passwordHash: "$argon2id$mock-hash-sankalp-ngo",
    role: "NGO",
    accountStatus: "PENDING",
    emailVerified: true,
    phoneVerified: false,
    lastLoginAt: daysAgo(2),
    createdAt: daysAgo(10),
    updatedAt: daysAgo(1),
  },

  // Volunteers / Couriers
  {
    _id: "usr-vol-01",
    name: "Rajesh Kumar (Volunteer Dispatch)",
    email: "rajesh.courier@foodconnect.demo",
    phone: "+919848022334",
    passwordHash: "$argon2id$mock-hash-rajesh-vol",
    role: "VOLUNTEER",
    accountStatus: "ACTIVE",
    emailVerified: true,
    phoneVerified: true,
    lastLoginAt: hourAgo(1),
    createdAt: daysAgo(25),
    updatedAt: hourAgo(1),
  },
  {
    _id: "usr-vol-02",
    name: "Swathi Naidu (Community Courier)",
    email: "swathi.naidu@foodconnect.demo",
    phone: "+919849033445",
    passwordHash: "$argon2id$mock-hash-swathi-vol",
    role: "VOLUNTEER",
    accountStatus: "ACTIVE",
    emailVerified: true,
    phoneVerified: true,
    lastLoginAt: hourAgo(6),
    createdAt: daysAgo(15),
    updatedAt: daysAgo(1),
  },

  // Platform Admin (Harshavardhan Pyla - Primary Root Authority)
  {
    _id: "usr-admin-01",
    name: "Harsha Vardhan Pyla",
    email: "admin@foodconnect.demo",
    phone: "+918912000000",
    passwordHash: "$argon2id$mock-hash-admin",
    role: "ADMIN",
    accountStatus: "ACTIVE",
    emailVerified: true,
    phoneVerified: true,
    lastLoginAt: hourAgo(1),
    createdAt: daysAgo(90),
    updatedAt: hourAgo(1),
  },
  {
    _id: "usr-admin-alias",
    name: "Harsha Vardhan Pyla",
    email: "admin@demo.org",
    phone: "+918912000001",
    passwordHash: "$argon2id$mock-hash-admin",
    role: "ADMIN",
    accountStatus: "ACTIVE",
    emailVerified: true,
    phoneVerified: true,
    lastLoginAt: hourAgo(1),
    createdAt: daysAgo(90),
    updatedAt: hourAgo(1),
  },
  {
    _id: "usr-admin-02",
    name: "Harsha Vardhan Pyla",
    email: "harshavardhan.pyla@foodconnect.demo",
    phone: "+918912567899",
    passwordHash: "$argon2id$mock-hash-admin",
    role: "ADMIN",
    accountStatus: "ACTIVE",
    emailVerified: true,
    phoneVerified: true,
    lastLoginAt: hourAgo(1),
    createdAt: daysAgo(60),
    updatedAt: hourAgo(1),
  },
]

// ============================================================================
// 2. MOCK DONOR PROFILES
// ============================================================================

export const SEED_DONOR_PROFILES: IDonorProfile[] = [
  {
    _id: "donor-vizag-01",
    userId: "usr-donor-01",
    donorType: "HOTEL",
    organizationName: "Hotel Daspalla Visakhapatnam",
    fssaiNumber: "10118028000123",
    contactPerson: "Venkata Raman",
    contactPhone: "+918912564800",
    contactEmail: "fnb@daspallavizag.demo",
    address: {
      street: "Surya Bagh, Jagadamba Center",
      area: "Jagadamba Center",
      city: "Visakhapatnam",
      state: "Andhra Pradesh",
      postalCode: "530020",
      landmarks: "Opposite Jagadamba Theatre Complex",
    },
    location: {
      type: "Point",
      coordinates: [83.3012, 17.7128], // [lng, lat]
    },
    pickupAvailability: {
      daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
      startTime: "14:00",
      endTime: "23:00",
      instructions: "Service lane gate #3 for collection vehicles",
    },
    preferredContactMethod: "PHONE",
    totalDonationsCount: 42,
    totalMealsRescued: 3850,
    createdAt: daysAgo(30),
    updatedAt: daysAgo(5),
  },
  {
    _id: "donor-vizag-02",
    userId: "usr-donor-02",
    donorType: "HOTEL",
    organizationName: "Novotel Visakhapatnam Varun Beach",
    fssaiNumber: "10119028000456",
    contactPerson: "Chef Ananya Roy",
    contactPhone: "+918913045600",
    contactEmail: "culinary@novotelvizag.demo",
    address: {
      street: "Dr NTR Beach Road, Krishna Nagar, Maharani Peta",
      area: "Beach Road",
      city: "Visakhapatnam",
      state: "Andhra Pradesh",
      postalCode: "530002",
      landmarks: "Next to Varun INOX Mall",
    },
    location: {
      type: "Point",
      coordinates: [83.3185, 17.7112],
    },
    pickupAvailability: {
      daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
      startTime: "15:30",
      endTime: "23:30",
      instructions: "Back receiving dock ramp accessible from beach road",
    },
    preferredContactMethod: "WHATSAPP",
    totalDonationsCount: 28,
    totalMealsRescued: 2600,
    createdAt: daysAgo(20),
    updatedAt: daysAgo(2),
  },
  {
    _id: "donor-vizag-03",
    userId: "usr-donor-03",
    donorType: "BUSINESS",
    organizationName: "Vizag Bakers Guild & Patisserie",
    fssaiNumber: "10120028000789",
    contactPerson: "K. Satyanarayana",
    contactPhone: "+918912781200",
    contactEmail: "orders@vizagbakers.demo",
    address: {
      street: "IT SEZ Main Road, Madhurawada",
      area: "Madhurawada",
      city: "Visakhapatnam",
      state: "Andhra Pradesh",
      postalCode: "530048",
      landmarks: "Near Hill No 2 IT Park",
    },
    location: {
      type: "Point",
      coordinates: [83.3542, 17.7981],
    },
    pickupAvailability: {
      daysOfWeek: [1, 2, 3, 4, 5, 6],
      startTime: "19:00",
      endTime: "21:30",
      instructions: "Pick up at front bakery counter before 9:30 PM",
    },
    preferredContactMethod: "PHONE",
    totalDonationsCount: 19,
    totalMealsRescued: 1140,
    createdAt: daysAgo(15),
    updatedAt: daysAgo(1),
  },
  {
    _id: "donor-vizag-04",
    userId: "usr-donor-04",
    donorType: "CATERING_SERVICE",
    organizationName: "Grand Horizon Banquet Caterers",
    fssaiNumber: "10117028000321",
    contactPerson: "K. V. Murthy",
    contactPhone: "+918912554400",
    contactEmail: "catering@murthyvizag.demo",
    address: {
      street: "Balaji Nagar, Siripuram Junction",
      area: "Siripuram",
      city: "Visakhapatnam",
      state: "Andhra Pradesh",
      postalCode: "530003",
      landmarks: "Behind VIP Road commercial plaza",
    },
    location: {
      type: "Point",
      coordinates: [83.3168, 17.7231],
    },
    pickupAvailability: {
      daysOfWeek: [0, 5, 6],
      startTime: "13:30",
      endTime: "16:00",
      instructions: "Direct loading into transport vans from kitchen gate",
    },
    preferredContactMethod: "PHONE",
    totalDonationsCount: 35,
    totalMealsRescued: 3150,
    createdAt: daysAgo(40),
    updatedAt: daysAgo(10),
  },
]

// ============================================================================
// 3. MOCK NGO PROFILES (VERIFIED RECIPIENT ORGANIZATIONS)
// ============================================================================

export const SEED_NGO_PROFILES: INGOProfile[] = [
  {
    _id: "ngo-vizag-01",
    userId: "usr-ngo-01",
    ngoName: "Sneha Sandhya Old Age & Care Trust",
    registrationNumber: "AP/2014/0078912",
    registrationDocumentUrls: [
      "https://storage.googleapis.com/foodconnect-demo/ngos/docs/sneha-sandhya-reg.pdf",
    ],
    verificationStatus: "VERIFIED",
    verifiedAt: daysAgo(55),
    verifiedBy: "usr-admin-01",
    contactPerson: {
      name: "Dr. P. S. Sarma",
      designation: "Managing Trustee",
      phone: "+918912789456",
      email: "trust@snehasandhya.demo",
    },
    address: {
      street: "Plot 42, Sector 4, MVP Colony",
      area: "MVP Colony",
      city: "Visakhapatnam",
      state: "Andhra Pradesh",
      postalCode: "530017",
    },
    location: {
      type: "Point",
      coordinates: [83.3426, 17.7386],
    },
    operatingAreas: [
      "MVP Colony",
      "Siripuram",
      "East Point Colony",
      "Waltair Uplands",
      "Rushikonda",
    ],
    foodTypesAccepted: [
      "COOKED_MEALS",
      "RAW_GRAINS_PULSES",
      "FRESH_PRODUCE",
      "DAIRY",
    ],
    dietaryPreferences: ["PURE_VEG", "VEG_AND_NON_VEG"],
    maximumMealCapacityPerDay: 250,
    pickupRadiusKm: 12.5,
    availability: {
      daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
      openTime: "07:00",
      closeTime: "21:00",
    },
    communitiesServed: [
      "Geriatric Elderly Residents",
      "Destitute Senior Women",
      "Day Care Patients",
    ],
    storageFacilities: [
      "COMMERCIAL_REFRIGERATION",
      "THERMAL_WARMERS",
      "DRY_VENTILATED_PANTRY",
    ],
    foodHandlingCapabilities: {
      hasThermalContainers: true,
      hasRefrigeration: true,
      hasDedicatedTransport: true,
      vehicleCount: 2,
      staffHandlerCount: 6,
    },
    totalNeedsCount: 28,
    totalMealsReceived: 2480,
    createdAt: daysAgo(60),
    updatedAt: daysAgo(2),
  },
  {
    _id: "ngo-vizag-02",
    userId: "usr-ngo-02",
    ngoName: "Prema Samajam Destitute Care Center",
    registrationNumber: "AP/1982/0001245",
    registrationDocumentUrls: [
      "https://storage.googleapis.com/foodconnect-demo/ngos/docs/prema-samajam-reg.pdf",
    ],
    verificationStatus: "VERIFIED",
    verifiedAt: daysAgo(48),
    verifiedBy: "usr-admin-01",
    contactPerson: {
      name: "Sister Mary Vasantha",
      designation: "Kitchen & Nutrition In-Charge",
      phone: "+918912567890",
      email: "care@premasamajam.demo",
    },
    address: {
      street: "Main Road, Daba Gardens",
      area: "Daba Gardens",
      city: "Visakhapatnam",
      state: "Andhra Pradesh",
      postalCode: "530020",
    },
    location: {
      type: "Point",
      coordinates: [83.2985, 17.7082],
    },
    operatingAreas: [
      "Daba Gardens",
      "Jagadamba Center",
      "RTC Complex Area",
      "Poorna Market",
    ],
    foodTypesAccepted: [
      "COOKED_MEALS",
      "PACKAGED_FOODS",
      "DAIRY",
      "BAKERY_ITEMS",
    ],
    dietaryPreferences: ["NO_RESTRICTION", "PURE_VEG", "VEG_AND_NON_VEG"],
    maximumMealCapacityPerDay: 300,
    pickupRadiusKm: 8.0,
    availability: {
      daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
      openTime: "06:30",
      closeTime: "22:00",
    },
    communitiesServed: [
      "Destitute Families",
      "Hospital Patient Attendants (KGH)",
      "Unsheltered Urban Homeless",
    ],
    storageFacilities: [
      "COMMERCIAL_REFRIGERATION",
      "THERMAL_WARMERS",
      "DRY_VENTILATED_PANTRY",
    ],
    foodHandlingCapabilities: {
      hasThermalContainers: true,
      hasRefrigeration: true,
      hasDedicatedTransport: true,
      vehicleCount: 1,
      staffHandlerCount: 8,
    },
    totalNeedsCount: 34,
    totalMealsReceived: 3120,
    createdAt: daysAgo(50),
    updatedAt: daysAgo(3),
  },
  {
    _id: "ngo-vizag-03",
    userId: "usr-ngo-03",
    ngoName: "Ashray Community Welfare Kitchen",
    registrationNumber: "AP/2018/0093821",
    registrationDocumentUrls: [
      "https://storage.googleapis.com/foodconnect-demo/ngos/docs/ashray-gajuwaka-reg.pdf",
    ],
    verificationStatus: "VERIFIED",
    verifiedAt: daysAgo(42),
    verifiedBy: "usr-admin-01",
    contactPerson: {
      name: "K. Appa Rao",
      designation: "Program Director",
      phone: "+918912445566",
      email: "kitchen@ashraygajuwaka.demo",
    },
    address: {
      street: "Industrial Estate Colony, Gajuwaka",
      area: "Gajuwaka",
      city: "Visakhapatnam",
      state: "Andhra Pradesh",
      postalCode: "530026",
    },
    location: {
      type: "Point",
      coordinates: [83.2184, 17.6892],
    },
    operatingAreas: [
      "Gajuwaka",
      "Auto Nagar",
      "Kurmannapalem",
      "Steel Plant Township",
    ],
    foodTypesAccepted: [
      "RAW_GRAINS_PULSES",
      "FRESH_PRODUCE",
      "COOKED_MEALS",
      "PACKAGED_FOODS",
    ],
    dietaryPreferences: ["VEG_AND_NON_VEG", "PURE_VEG"],
    maximumMealCapacityPerDay: 200,
    pickupRadiusKm: 15.0,
    availability: {
      daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
      openTime: "08:00",
      closeTime: "20:00",
    },
    communitiesServed: [
      "Daily-Wage Migrant Workers",
      "Informal Settlement Children",
      "Industrial Labor Families",
    ],
    storageFacilities: [
      "DRY_VENTILATED_PANTRY",
      "COMMERCIAL_REFRIGERATION",
    ],
    foodHandlingCapabilities: {
      hasThermalContainers: false,
      hasRefrigeration: true,
      hasDedicatedTransport: true,
      vehicleCount: 1,
      staffHandlerCount: 4,
    },
    totalNeedsCount: 22,
    totalMealsReceived: 1850,
    createdAt: daysAgo(45),
    updatedAt: daysAgo(4),
  },
  {
    _id: "ngo-vizag-04",
    userId: "usr-ngo-04",
    ngoName: "Sankalp Coastal Fisher Welfare Trust",
    registrationNumber: "AP/2022/0114522",
    registrationDocumentUrls: [
      "https://storage.googleapis.com/foodconnect-demo/ngos/docs/sankalp-reg-pending.pdf",
    ],
    verificationStatus: "UNDER_REVIEW", // Demonstrates the verification lifecycle state
    contactPerson: {
      name: "M. Jagannath",
      designation: "Coordinator",
      phone: "+918912889900",
      email: "contact@sankalpcoast.demo",
    },
    address: {
      street: "Fishing Village Road, Rushikonda",
      area: "Rushikonda",
      city: "Visakhapatnam",
      state: "Andhra Pradesh",
      postalCode: "530045",
    },
    location: {
      type: "Point",
      coordinates: [83.3821, 17.7854],
    },
    operatingAreas: ["Rushikonda", "Sagar Nagar", "Bheemili Road"],
    foodTypesAccepted: ["RAW_GRAINS_PULSES", "PACKAGED_FOODS", "FRESH_PRODUCE"],
    dietaryPreferences: ["NO_RESTRICTION"],
    maximumMealCapacityPerDay: 150,
    pickupRadiusKm: 10.0,
    availability: {
      daysOfWeek: [1, 2, 3, 4, 5, 6],
      openTime: "09:00",
      closeTime: "18:00",
    },
    communitiesServed: ["Coastal Artisanal Fisher Families", "Low-income Beach Laborers"],
    storageFacilities: ["DRY_VENTILATED_PANTRY"],
    foodHandlingCapabilities: {
      hasThermalContainers: false,
      hasRefrigeration: false,
      hasDedicatedTransport: false,
      vehicleCount: 0,
      staffHandlerCount: 3,
    },
    totalNeedsCount: 4,
    totalMealsReceived: 250,
    createdAt: daysAgo(10),
    updatedAt: daysAgo(1),
  },
]

// ============================================================================
// 4. MOCK ACTIVE FOOD NEEDS (COMMUNITY DEMAND)
// ============================================================================

export const SEED_NEEDS: INeed[] = [
  {
    _id: "need-vizag-01",
    ngoId: "ngo-vizag-01",
    beneficiaryCategory: "Sheltered Senior Citizens",
    location: {
      address: "Sector 4 Dining Hall, MVP Colony",
      area: "MVP Colony",
      city: "Visakhapatnam",
    },
    geoPoint: {
      type: "Point",
      coordinates: [83.3426, 17.7386],
    },
    peopleNeedingFood: 80,
    quantityRequired: 80,
    unit: "portions",
    quantityFulfilled: 50,
    quantityRemaining: 30, // Invariant: 80 - 50 = 30 remaining
    foodType: "COOKED_MEALS",
    dietaryRequirements: "PURE_VEG",
    urgency: "IMMEDIATE",
    requiredBy: hoursFromNow(3),
    additionalRequirements: "Mild vegetarian meals with soft rice and dal preferred for senior residents.",
    verificationState: "NGO_VERIFIED",
    status: "PARTIALLY_FULFILLED",
    expiresAt: hoursFromNow(5),
    version: 4,
    createdAt: hourAgo(4),
    updatedAt: hourAgo(1),
  },
  {
    _id: "need-vizag-02",
    ngoId: "ngo-vizag-02",
    beneficiaryCategory: "Destitute Care & Hospital Patient Attendants",
    location: {
      address: "Main Road Distribution Counter, Daba Gardens",
      area: "Daba Gardens",
      city: "Visakhapatnam",
    },
    geoPoint: {
      type: "Point",
      coordinates: [83.2985, 17.7082],
    },
    peopleNeedingFood: 120,
    quantityRequired: 120,
    unit: "portions",
    quantityFulfilled: 0,
    quantityRemaining: 120,
    foodType: "COOKED_MEALS",
    dietaryRequirements: "NO_RESTRICTION",
    urgency: "IMMEDIATE",
    requiredBy: hoursFromNow(4),
    additionalRequirements: "Wholesome dinner meal portions for night distribution.",
    verificationState: "NGO_VERIFIED",
    status: "ACTIVE",
    expiresAt: hoursFromNow(6),
    version: 1,
    createdAt: hourAgo(2),
    updatedAt: hourAgo(2),
  },
  {
    _id: "need-vizag-03",
    ngoId: "ngo-vizag-03",
    beneficiaryCategory: "Daily-Wage Migrant Workers & Informal Settlement",
    location: {
      address: "Auto Nagar Shed 14, Gajuwaka",
      area: "Gajuwaka",
      city: "Visakhapatnam",
    },
    geoPoint: {
      type: "Point",
      coordinates: [83.2184, 17.6892],
    },
    peopleNeedingFood: 150,
    quantityRequired: 60,
    unit: "kg",
    quantityFulfilled: 60,
    quantityRemaining: 0, // Invariant: 60 - 60 = 0 (FULFILLED)
    foodType: "RAW_GRAINS_PULSES",
    dietaryRequirements: "PURE_VEG",
    urgency: "HIGH",
    requiredBy: hoursFromNow(24),
    additionalRequirements: "Rice, Toor dal, cooking oil for community kitchen batch cooking.",
    verificationState: "NGO_VERIFIED",
    status: "FULFILLED",
    expiresAt: hoursFromNow(28),
    version: 3,
    createdAt: daysAgo(1),
    updatedAt: hourAgo(3),
  },
  {
    _id: "need-vizag-04",
    ngoId: "ngo-vizag-04",
    beneficiaryCategory: "Coastal Artisanal Fisher Families",
    location: {
      address: "Community Shed, Sagar Nagar Coast",
      area: "Rushikonda",
      city: "Visakhapatnam",
    },
    geoPoint: {
      type: "Point",
      coordinates: [83.3821, 17.7854],
    },
    peopleNeedingFood: 90,
    quantityRequired: 50,
    unit: "kg",
    quantityFulfilled: 0,
    quantityRemaining: 50,
    foodType: "RAW_GRAINS_PULSES",
    dietaryRequirements: "PURE_VEG",
    urgency: "FLEXIBLE",
    requiredBy: hoursFromNow(48),
    additionalRequirements: "Dry grains and pulses for ration distribution.",
    verificationState: "PENDING_AUDIT",
    status: "ACTIVE",
    expiresAt: hoursFromNow(72),
    version: 1,
    createdAt: daysAgo(1),
    updatedAt: daysAgo(1),
  },
]

// ============================================================================
// 5. MOCK DONATIONS (SURPLUS FOOD LOTS)
// ============================================================================

export const SEED_DONATIONS: IDonation[] = [
  {
    _id: "don-vizag-01",
    donorId: "donor-vizag-01",
    foodName: "Fresh Lunch Buffet Surplus (Rice, Sambar, Sabzi)",
    foodCategory: "COOKED_MEALS",
    vegNonVeg: "VEG",
    quantity: 100,
    unit: "portions",
    preparedAt: hourAgo(3),
    safeConsumptionDeadline: hoursFromNow(4),
    storageCondition: "HOT_HEATED",
    packagingCondition: "STAINLESS_STEEL_VATS",
    allergens: ["Gluten", "Dairy"],
    notes: "Food held in heated bain-marie until packout. Needs thermal collection vessels.",
    photoReferences: [
      "https://storage.googleapis.com/foodconnect-demo/donations/photos/lot-8924-a.jpg",
    ],
    pickupAddress: {
      street: "Surya Bagh, Jagadamba Center",
      area: "Jagadamba Center",
      city: "Visakhapatnam",
      postalCode: "530020",
      instructions: "Loading bay #2 behind main banquet entrance",
    },
    pickupLocation: {
      type: "Point",
      coordinates: [83.3012, 17.7128],
    },
    pickupAvailabilityWindow: {
      start: hourAgo(1),
      end: hoursFromNow(2),
    },
    donorAcknowledgement: {
      accepted: true,
      timestamp: hourAgo(2),
      ipAddress: "103.241.138.45",
      statement:
        "FoodConnect does not certify food safety. Donors are responsible for providing accurate food information.",
    },
    status: "ACCEPTED",
    activeMatchId: "match-vizag-01",
    assignedCollectionId: "col-vizag-01",
    version: 3,
    createdAt: hourAgo(2),
    updatedAt: hourAgo(1),
  },
  {
    _id: "don-vizag-02",
    donorId: "donor-vizag-02",
    foodName: "Grand Dinner Buffet Surplus (Veg Biryani & Chicken Curry)",
    foodCategory: "COOKED_MEALS",
    vegNonVeg: "BOTH",
    quantity: 120,
    unit: "portions",
    preparedAt: hourAgo(1),
    safeConsumptionDeadline: hoursFromNow(5),
    storageCondition: "HOT_HEATED",
    packagingCondition: "COMMERCIAL_SEALED",
    allergens: ["Dairy"],
    notes: "Fresh corporate banquet surplus. Pre-packed in heat-sealed food-grade aluminum trays.",
    photoReferences: [
      "https://storage.googleapis.com/foodconnect-demo/donations/photos/novotel-lot-02.jpg",
    ],
    pickupAddress: {
      street: "Dr NTR Beach Road, Krishna Nagar",
      area: "Beach Road",
      city: "Visakhapatnam",
      postalCode: "530002",
      instructions: "Receiving ramp behind Varun INOX mall",
    },
    pickupLocation: {
      type: "Point",
      coordinates: [83.3185, 17.7112],
    },
    pickupAvailabilityWindow: {
      start: hourAgo(0.5),
      end: hoursFromNow(3),
    },
    donorAcknowledgement: {
      accepted: true,
      timestamp: hourAgo(1),
      ipAddress: "103.241.138.46",
      statement:
        "FoodConnect does not certify food safety. Donors are responsible for providing accurate food information.",
    },
    status: "AVAILABLE",
    activeMatchId: "match-vizag-02",
    version: 1,
    createdAt: hourAgo(1),
    updatedAt: hourAgo(1),
  },
  {
    _id: "don-vizag-03",
    donorId: "donor-vizag-03",
    foodName: "Fresh Baked Buns, Whole Wheat Bread & Savory Rolls",
    foodCategory: "BAKERY_ITEMS",
    vegNonVeg: "VEG",
    quantity: 60,
    unit: "packets",
    preparedAt: hourAgo(4),
    safeConsumptionDeadline: hoursFromNow(36),
    storageCondition: "ROOM_TEMPERATURE",
    packagingCondition: "FOOD_GRADE_DISPOSABLE",
    allergens: ["Gluten"],
    notes: "End-of-day surplus packaged in food-grade kraft bags.",
    photoReferences: [
      "https://storage.googleapis.com/foodconnect-demo/donations/photos/bakery-lot-03.jpg",
    ],
    pickupAddress: {
      street: "IT SEZ Main Road, Madhurawada",
      area: "Madhurawada",
      city: "Visakhapatnam",
      postalCode: "530048",
      instructions: "Collect at front service counter",
    },
    pickupLocation: {
      type: "Point",
      coordinates: [83.3542, 17.7981],
    },
    pickupAvailabilityWindow: {
      start: hourAgo(2),
      end: hoursFromNow(4),
    },
    donorAcknowledgement: {
      accepted: true,
      timestamp: hourAgo(2),
      statement:
        "FoodConnect does not certify food safety. Donors are responsible for providing accurate food information.",
    },
    status: "AVAILABLE",
    version: 1,
    createdAt: hourAgo(2),
    updatedAt: hourAgo(2),
  },
  {
    _id: "don-vizag-04",
    donorId: "donor-vizag-04",
    foodName: "Sona Masoori Rice & Toor Dal Surplus Sacks",
    foodCategory: "RAW_GRAINS_PULSES",
    vegNonVeg: "VEG",
    quantity: 60,
    unit: "kg",
    preparedAt: daysAgo(2),
    safeConsumptionDeadline: hoursFromNow(720), // 30 days
    storageCondition: "ROOM_TEMPERATURE",
    packagingCondition: "CORRUGATED_BOXES",
    allergens: [],
    notes: "Sealed manufacturer bags of grain from completed wedding contract.",
    photoReferences: [
      "https://storage.googleapis.com/foodconnect-demo/donations/photos/grain-lot-04.jpg",
    ],
    pickupAddress: {
      street: "Balaji Nagar, Siripuram Junction",
      area: "Siripuram",
      city: "Visakhapatnam",
      postalCode: "530003",
    },
    pickupLocation: {
      type: "Point",
      coordinates: [83.3168, 17.7231],
    },
    pickupAvailabilityWindow: {
      start: daysAgo(1),
      end: hoursFromNow(12),
    },
    donorAcknowledgement: {
      accepted: true,
      timestamp: daysAgo(1),
      statement:
        "FoodConnect does not certify food safety. Donors are responsible for providing accurate food information.",
    },
    status: "DISTRIBUTED",
    assignedCollectionId: "col-vizag-02",
    version: 4,
    createdAt: daysAgo(1),
    updatedAt: hourAgo(2),
  },
]

// ============================================================================
// 6. MOCK MATCH RECOMMENDATIONS
// ============================================================================

export const SEED_MATCHES: IMatch[] = [
  {
    _id: "match-vizag-01",
    donationId: "don-vizag-01",
    needId: "need-vizag-01",
    ngoId: "ngo-vizag-01",
    score: 92,
    distanceKm: 3.2,
    factorScores: {
      distanceScore: 96,
      foodCompatibilityScore: 98,
      quantityAlignmentScore: 90,
      urgencyScore: 92,
      deadlineScore: 92,
      storageCapacityScore: 95,
    },
    explanation: {
      summary:
        "High compatibility: 3.2 km distance via Beach Road with thermal holding equipment verified.",
      positiveFactors: [
        "Transit time under 12 minutes",
        "Pure vegetarian cooked food matches elderly dietary mandate",
        "NGO has verified thermal warmers",
      ],
      riskFactors: [
        "Perishable hot meal: collection must commence within 90 minutes",
      ],
    },
    status: "ACCEPTED",
    proposedAt: hourAgo(2),
    respondedAt: hourAgo(1.5),
    expiresAt: hoursFromNow(1),
    createdAt: hourAgo(2),
    updatedAt: hourAgo(1.5),
  },
  {
    _id: "match-vizag-02",
    donationId: "don-vizag-02",
    needId: "need-vizag-02",
    ngoId: "ngo-vizag-02",
    score: 95,
    distanceKm: 2.4,
    factorScores: {
      distanceScore: 98,
      foodCompatibilityScore: 97,
      quantityAlignmentScore: 96,
      urgencyScore: 93,
      deadlineScore: 94,
      storageCapacityScore: 96,
    },
    explanation: {
      summary:
        "Optimal match: 2.4 km straight transit from Novotel Beach Road to Prema Samajam Daba Gardens.",
      positiveFactors: [
        "120 portions exactly satisfies target need of 120",
        "8-minute direct transit corridor",
        "Pre-sealed aluminum trays simplify sanitary service",
      ],
      riskFactors: [
        "Dinner service deadline within 4 hours",
      ],
    },
    status: "PROPOSED",
    proposedAt: hourAgo(1),
    expiresAt: hoursFromNow(2),
    createdAt: hourAgo(1),
    updatedAt: hourAgo(1),
  },
]

// ============================================================================
// 7. MOCK COLLECTIONS (DISPATCH & CUSTODY)
// ============================================================================

export const SEED_COLLECTIONS: ICollection[] = [
  {
    _id: "col-vizag-01",
    donationId: "don-vizag-01",
    ngoId: "ngo-vizag-01",
    needId: "need-vizag-01",
    collectorType: "VOLUNTEER_PARTNER",
    volunteerId: "usr-vol-01", // Assigned to volunteer Rajesh Kumar
    pickupAddress: {
      street: "Surya Bagh, Jagadamba Center",
      area: "Jagadamba Center",
      city: "Visakhapatnam",
    },
    pickupCoordinates: {
      type: "Point",
      coordinates: [83.3012, 17.7128],
    },
    scheduledAt: hourAgo(1),
    assignedAt: hourAgo(1.5),
    enRouteAt: hourAgo(1.2),
    arrivedAt: hourAgo(1),
    collectedAt: hourAgo(0.8),
    status: "COLLECTED",
    collectionPhotos: [
      "https://storage.googleapis.com/foodconnect-demo/collections/proofs/col-01-dock.jpg",
    ],
    temperatureAtPickupCelsius: 64.5,
    notes: "Food inspected and securely placed in insulated transport boxes.",
    createdAt: hourAgo(1.5),
    updatedAt: hourAgo(0.8),
  },
  {
    _id: "col-vizag-02",
    donationId: "don-vizag-04",
    ngoId: "ngo-vizag-03",
    needId: "need-vizag-03",
    collectorType: "NGO_INTERNAL",
    pickupAddress: {
      street: "Balaji Nagar, Siripuram Junction",
      area: "Siripuram",
      city: "Visakhapatnam",
    },
    pickupCoordinates: {
      type: "Point",
      coordinates: [83.3168, 17.7231],
    },
    scheduledAt: daysAgo(1),
    assignedAt: daysAgo(1),
    collectedAt: daysAgo(0.9),
    status: "COLLECTED",
    collectionPhotos: [
      "https://storage.googleapis.com/foodconnect-demo/collections/proofs/col-02-grain.jpg",
    ],
    notes: "60 kg sacks loaded onto NGO pickup mini-truck.",
    createdAt: daysAgo(1),
    updatedAt: daysAgo(0.9),
  },
  {
    _id: "col-vizag-03",
    donationId: "don-vizag-02",
    ngoId: "ngo-vizag-02",
    needId: "need-vizag-02",
    collectorType: "VOLUNTEER_PARTNER",
    pickupAddress: {
      street: "Dr NTR Beach Road, Coastal Corridor",
      area: "Beach Road",
      city: "Visakhapatnam",
    },
    pickupCoordinates: {
      type: "Point",
      coordinates: [83.3245, 17.7142],
    },
    scheduledAt: hoursFromNow(1),
    assignedAt: hourAgo(0.5),
    status: "ASSIGNED",
    collectionPhotos: [],
    notes: "Hot buffet portions held in insulated thermal containers at Novotel receiving bay.",
    createdAt: hourAgo(0.5),
    updatedAt: hourAgo(0.5),
  },
]

// ============================================================================
// 8. MOCK DISTRIBUTIONS (PROOF OF IMPACT & VERIFICATION)
// ============================================================================

export const SEED_DISTRIBUTIONS: IDistribution[] = [
  {
    _id: "dist-vizag-01",
    donationId: "don-vizag-01",
    ngoId: "ngo-vizag-01",
    needId: "need-vizag-01",
    collectionId: "col-vizag-01",
    quantityDistributed: 50,
    unit: "portions",
    peopleServed: 50,
    distributionTimestamp: hourAgo(0.5),
    distributionLocation: {
      communityCenterName: "Sneha Sandhya Community Dining Pavilion",
      street: "Sector 4, MVP Colony",
      area: "MVP Colony",
      city: "Visakhapatnam",
    },
    geoPoint: {
      type: "Point",
      coordinates: [83.3426, 17.7386],
    },
    evidencePhotos: [
      "https://storage.googleapis.com/foodconnect-demo/distributions/proofs/dist-01-serving.jpg",
      "https://storage.googleapis.com/foodconnect-demo/distributions/proofs/dist-01-audit.jpg",
    ],
    description:
      "50 fresh warm lunch portions distributed directly to senior citizens and nursing residents.",
    submittedBy: "usr-ngo-01",
    verificationStatus: "VERIFIED",
    verifiedBy: "usr-admin-01",
    verifiedAt: hourAgo(0.2),
    impactMetrics: {
      mealsDelivered: 50,
      estimatedKgSaved: 17.5,
      co2KgPrevented: 43.75,
    },
    createdAt: hourAgo(0.5),
    updatedAt: hourAgo(0.2),
  },
  {
    _id: "dist-vizag-02",
    donationId: "don-vizag-04",
    ngoId: "ngo-vizag-03",
    needId: "need-vizag-03",
    collectionId: "col-vizag-02",
    quantityDistributed: 60,
    unit: "kg",
    peopleServed: 150,
    distributionTimestamp: daysAgo(0.5),
    distributionLocation: {
      communityCenterName: "Auto Nagar Community Kitchen",
      street: "Industrial Estate, Gajuwaka",
      area: "Gajuwaka",
      city: "Visakhapatnam",
    },
    geoPoint: {
      type: "Point",
      coordinates: [83.2184, 17.6892],
    },
    evidencePhotos: [
      "https://storage.googleapis.com/foodconnect-demo/distributions/proofs/dist-02-grain.jpg",
    ],
    description:
      "60 kg dry grain ration packages distributed to 150 family members in Auto Nagar settlement.",
    submittedBy: "usr-ngo-03",
    verificationStatus: "VERIFIED",
    verifiedBy: "usr-admin-01",
    verifiedAt: daysAgo(0.4),
    impactMetrics: {
      mealsDelivered: 150,
      estimatedKgSaved: 60.0,
      co2KgPrevented: 150.0,
    },
    createdAt: daysAgo(0.5),
    updatedAt: daysAgo(0.4),
  },
]

// ============================================================================
// 9. MOCK AUDIT LOGS (IMMUTABLE CHRONOLOGICAL LEDGER)
// ============================================================================

export const SEED_AUDIT_LOGS: IAuditLog[] = [
  {
    _id: "audit-vizag-01",
    actorId: "usr-ngo-01",
    actorRole: "NGO",
    action: "NEED_CREATED",
    entityType: "Need",
    entityId: "need-vizag-01",
    newState: {
      quantityRequired: 80,
      beneficiaryCategory: "Sheltered Senior Citizens",
      status: "ACTIVE",
    },
    timestamp: hourAgo(4),
  },
  {
    _id: "audit-vizag-02",
    actorId: "usr-donor-01",
    actorRole: "DONOR",
    action: "DONATION_CREATED",
    entityType: "Donation",
    entityId: "don-vizag-01",
    newState: {
      foodName: "Fresh Lunch Buffet Surplus (Rice, Sambar, Sabzi)",
      quantity: 100,
      status: "AVAILABLE",
    },
    timestamp: hourAgo(2),
  },
  {
    _id: "audit-vizag-03",
    actorId: "usr-ngo-01",
    actorRole: "NGO",
    action: "MATCH_ACCEPTED",
    entityType: "Match",
    entityId: "match-vizag-01",
    newState: {
      status: "ACCEPTED",
    },
    timestamp: hourAgo(1.5),
  },
  {
    _id: "audit-vizag-04",
    actorId: "usr-vol-01",
    actorRole: "VOLUNTEER",
    action: "COLLECTION_STATUS_CHANGED",
    entityType: "Collection",
    entityId: "col-vizag-01",
    previousState: { status: "ASSIGNED" },
    newState: { status: "COLLECTED", temperatureAtPickupCelsius: 64.5 },
    timestamp: hourAgo(0.8),
  },
  {
    _id: "audit-vizag-05",
    actorId: "usr-admin-01",
    actorRole: "ADMIN",
    action: "DISTRIBUTION_VERIFIED",
    entityType: "Distribution",
    entityId: "dist-vizag-01",
    previousState: { verificationStatus: "PENDING" },
    newState: { verificationStatus: "VERIFIED" },
    timestamp: hourAgo(0.2),
  },
]

// ============================================================================
// 10. MOCK NOTIFICATIONS
// ============================================================================

export const SEED_NOTIFICATIONS: INotification[] = [
  {
    _id: "notif-vizag-01",
    userId: "usr-donor-01",
    eventType: "DONATION_ACCEPTED",
    title: "Donation Accepted by Sneha Sandhya",
    message:
      "Your surplus lot 'Fresh Lunch Buffet Surplus' has been accepted. Volunteer courier Rajesh Kumar is dispatched.",
    entityType: "Donation",
    entityId: "don-vizag-01",
    actionUrl: "/donations/don-vizag-01",
    isRead: false,
    createdAt: hourAgo(1.5),
  },
  {
    _id: "notif-vizag-02",
    userId: "usr-ngo-01",
    eventType: "NEW_MATCHING_DONATION",
    title: "High Compatibility Match Found (92%)",
    message:
      "Hotel Daspalla registered 100 portions of fresh vegetarian meals 3.2 km away matching your lunch need.",
    entityType: "Match",
    entityId: "match-vizag-01",
    actionUrl: "/matches/match-vizag-01",
    isRead: true,
    readAt: hourAgo(1.8),
    createdAt: hourAgo(2),
  },
  {
    _id: "notif-vizag-03",
    userId: "usr-vol-01",
    eventType: "COLLECTION_ASSIGNED",
    title: "New Surplus Pickup Task Assigned",
    message:
      "Please proceed to Hotel Daspalla (Jagadamba Center) for 100 warm meals transport to MVP Colony.",
    entityType: "Collection",
    entityId: "col-vizag-01",
    actionUrl: "/collections/col-vizag-01",
    isRead: false,
    createdAt: hourAgo(1.5),
  },
  {
    _id: "notif-vizag-04",
    userId: "usr-admin-01",
    eventType: "DISTRIBUTION_SUBMITTED",
    title: "New Distribution Proof Awaiting Verification",
    message:
      "Sneha Sandhya submitted handover photos for 50 meals served in MVP Colony.",
    entityType: "Distribution",
    entityId: "dist-vizag-01",
    actionUrl: "/admin/distributions/dist-vizag-01",
    isRead: true,
    readAt: hourAgo(0.3),
    createdAt: hourAgo(0.5),
  },
]
