import { MapLocation } from "@/lib/types/map"

/**
 * Visakhapatnam Geographic Center & Default Bounds
 * Center: Near Siripuram / Waltair Uplands, Visakhapatnam, Andhra Pradesh
 */
export const VIZAG_CENTER = {
  latitude: 17.7215,
  longitude: 83.3155,
  zoom: 12,
  city: "Visakhapatnam",
  state: "Andhra Pradesh",
  country: "India",
}

/**
 * Structured demonstration markers for Visakhapatnam.
 * Note: These are illustrative demonstration coordinates and do not represent real-world live listings.
 */
export const VIZAG_DEMO_LOCATIONS: MapLocation[] = [
  {
    id: "need-vizag-01",
    type: "need",
    name: "Sneha Sandhya Senior Care Home",
    organization: "Sneha Sandhya Trust (Demo NGO)",
    latitude: 17.7386,
    longitude: 83.3426,
    area: "MVP Colony (Sector 4)",
    status: "Active Need",
    quantity: "80 warm dinner portions",
    foodType: "Cooked Meals & Prepared Trays",
    urgency: "Immediate",
    peopleCount: 80,
    details: "Daily evening dinner support needed for 80 elderly residents.",
  },
  {
    id: "donation-vizag-01",
    type: "donation",
    name: "Banquet Hall Surplus — Hotel Daspalla",
    organization: "Grand Banquet Catering (Demo Donor)",
    latitude: 17.7128,
    longitude: 83.3012,
    area: "Jagadamba Center",
    status: "Available",
    quantity: "100 Fresh Cooked Meals",
    foodType: "Rice, Dal & Mixed Vegetable Curry",
    urgency: "Immediate",
    details: "Fresh lunch buffet surplus kept in insulated warming pans. Pickup within 3 hrs.",
  },
  {
    id: "ngo-vizag-01",
    type: "ngo",
    name: "Chaitanya Youth Community Kitchen",
    organization: "Chaitanya Foundation (Demo NGO)",
    latitude: 17.7231,
    longitude: 83.3168,
    area: "Siripuram Junction",
    status: "Verified",
    quantity: "Capacity: 250 meals/day",
    foodType: "Cooked food, dry grains, bakery items",
    details: "Equipped with refrigerated holding and 2 dedicated collection two-wheelers.",
  },
  {
    id: "need-vizag-02",
    type: "need",
    name: "Karunya Children & Family Shelter",
    organization: "Karunya Society (Demo NGO)",
    latitude: 17.6892,
    longitude: 83.2184,
    area: "Gajuwaka Industrial Belt",
    status: "Active Need",
    quantity: "120 breakfast packs",
    foodType: "Idli, Upma & Fresh Fruit",
    urgency: "High",
    peopleCount: 120,
    details: "Morning nutrition distribution for daily wage migrant families and children.",
  },
  {
    id: "ngo-vizag-02",
    type: "ngo",
    name: "Mother Teresa Welfare Home",
    organization: "Mother Teresa Care (Demo NGO)",
    latitude: 17.7082,
    longitude: 83.2985,
    area: "Daba Gardens",
    status: "Verified",
    quantity: "Capacity: 180 meals/day",
    foodType: "Cooked meals, dairy, packaged foods",
    details: "Serving destitutes and hospital attendants near KGH hospital area.",
  },
  {
    id: "need-vizag-03",
    type: "need",
    name: "Sankalp Coastal Fisher Community Center",
    organization: "Sankalp Coastal Trust (Demo NGO)",
    latitude: 17.7854,
    longitude: 83.3821,
    area: "Rushikonda / Sagar Nagar",
    status: "Partially Fulfilled",
    quantity: "50 kg staples & grain",
    foodType: "Rice, Lentils, Oil & Bakery",
    urgency: "Flexible",
    peopleCount: 160,
    details: "Weekly ration bank for low-income coastal community during non-fishing window.",
  },
  {
    id: "donation-vizag-02",
    type: "donation",
    name: "Fresh Bake Outlet Surplus",
    organization: "Vizag Bakers Guild (Demo Donor)",
    latitude: 17.7981,
    longitude: 83.3542,
    area: "Madhurawada IT SEZ",
    status: "Available",
    quantity: "60 fresh loaves & buns",
    foodType: "Whole wheat bread, milk buns",
    urgency: "High",
    details: "End-of-day fresh baked goods packed in food-grade kraft bags.",
  },
  {
    id: "ngo-vizag-03",
    type: "ngo",
    name: "Aasra Urban Homeless Relief Center",
    organization: "Aasra Foundation (Demo NGO)",
    latitude: 17.7018,
    longitude: 83.2912,
    area: "Railway Station Road / RTC Complex",
    status: "Verified",
    quantity: "Capacity: 200 meals/day",
    foodType: "Prepared warm meals, sandwiches",
    details: "Night shelter feeding station operating near Visakhapatnam railway transit hub.",
  },
]

export const VIZAG_AREAS = [
  "All Vizag Areas",
  "Siripuram",
  "MVP Colony",
  "Beach Road",
  "Gajuwaka",
  "Madhurawada",
  "Rushikonda",
  "Dwaraka Nagar",
  "Akkayyapalem",
  "Seethammadhara",
  "NAD",
  "Kurmannapalem",
  "Pendurthi",
  "Gopalapatnam",
  "Kancharapalem",
  "Maddilapalem",
  "Jagadamba Junction",
  "Waltair",
  "Yendada",
] as const
